From ubuntu:18.04

RUN apt-get -y dist-upgrade
RUN apt-get -y update

RUN apt-get -y install build-essential curl git cmake libpng-dev

RUN git clone https://github.com/roboception/rc_genicam_api.git

RUN cd rc_genicam_api && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/opt/pllee4 .. && make && make install

ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/pllee4/lib"

RUN /opt/pllee4/bin/gc_info