name: Building and pushing of latest docker images
"on":
  schedule:
    - cron: '0 12 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ubuntu-18.04
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:ubuntu-ci/18.04"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ci:18.04

      - name: Build and push ubuntu-20.04
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:ubuntu-ci/20.04"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ci:20.04

      - name: Build and push ubuntu-22.04
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:ubuntu-ci/22.04"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ci:22.04

      - name: Build and push zephyr-3.3-focal
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:ubuntu-ci/zephyr-3.3-focal"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ci:zephyr-3.3-focal

      - name: Build and push control-toolbox
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:project/control-toolbox"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project:control-toolbox